version: '3.8'
services:
  spring-petclinic:
    image: petclinic-image:latest
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_PASS=petclinic
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=petclinic
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_DB=petclinic
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
